#pragma once

#include "pch.h"

namespace fr {
	#ifdef FR_WINDOWS
		#define KEY_SPACE              32
		#define KEY_APOSTROPHE         39 
		#define KEY_COMMA              44 
		#define KEY_MINUS              45  
		#define KEY_PERIOD             46  
		#define KEY_SLASH              47 
		#define KEY_0                  48
		#define KEY_1                  49
		#define KEY_2                  50
		#define KEY_3                  51
		#define KEY_4                  52
		#define KEY_5                  53
		#define KEY_6                  54
		#define KEY_7                  55
		#define KEY_8                  56
		#define KEY_9                  57
		#define KEY_SEMICOLON          59 
		#define KEY_EQUAL              61 
		#define KEY_A                  65
		#define KEY_B                  66
		#define KEY_C                  67
		#define KEY_D                  68
		#define KEY_E                  69
		#define KEY_F                  70
		#define KEY_G                  71
		#define KEY_H                  72
		#define KEY_I                  73
		#define KEY_J                  74
		#define KEY_K                  75
		#define KEY_L                  76
		#define KEY_M                  77
		#define KEY_N                  78
		#define KEY_O                  79
		#define KEY_P                  80
		#define KEY_Q                  81
		#define KEY_R                  82
		#define KEY_S                  83
		#define KEY_T                  84
		#define KEY_U                  85
		#define KEY_V                  86
		#define KEY_W                  87
		#define KEY_X                  88
		#define KEY_Y                  89
		#define KEY_Z                  90
		#define KEY_LEFT_BRACKET       91 
		#define KEY_BACKSLASH          92 
		#define KEY_RIGHT_BRACKET      93 
		#define KEY_GRAVE_ACCENT       96 
		#define KEY_WORLD_1            161 
		#define KEY_WORLD_2            162 
		#define KEY_ESCAPE             256
		#define KEY_ENTER              257
		#define KEY_TAB                258
		#define KEY_BACKSPACE          259
		#define KEY_INSERT             260
		#define KEY_DELETE             261
		#define KEY_RIGHT              262
		#define KEY_LEFT               263
		#define KEY_DOWN               264
		#define KEY_UP                 265
		#define KEY_PAGE_UP            266
		#define KEY_PAGE_DOWN          267
		#define KEY_HOME               268
		#define KEY_END                269
		#define KEY_CAPS_LOCK          280
		#define KEY_SCROLL_LOCK        281
		#define KEY_NUM_LOCK           282
		#define KEY_PRINT_SCREEN       283
		#define KEY_PAUSE              284
		#define KEY_F1                 290
		#define KEY_F2                 291
		#define KEY_F3                 292
		#define KEY_F4                 293
		#define KEY_F5                 294
		#define KEY_F6                 295
		#define KEY_F7                 296
		#define KEY_F8                 297
		#define KEY_F9                 298
		#define KEY_F10                299
		#define KEY_F11                300
		#define KEY_F12                301
		#define KEY_F13                302
		#define KEY_F14                303
		#define KEY_F15                304
		#define KEY_F16                305
		#define KEY_F17                306
		#define KEY_F18                307
		#define KEY_F19                308
		#define KEY_F20                309
		#define KEY_F21                310
		#define KEY_F22                311
		#define KEY_F23                312
		#define KEY_F24                313
		#define KEY_F25                314
		#define KEY_KP_0               320
		#define KEY_KP_1               321
		#define KEY_KP_2               322
		#define KEY_KP_3               323
		#define KEY_KP_4               324
		#define KEY_KP_5               325
		#define KEY_KP_6               326
		#define KEY_KP_7               327
		#define KEY_KP_8               328
		#define KEY_KP_9               329
		#define KEY_KP_DECIMAL         330
		#define KEY_KP_DIVIDE          331
		#define KEY_KP_MULTIPLY        332
		#define KEY_KP_SUBTRACT        333
		#define KEY_KP_ADD             334
		#define KEY_KP_ENTER           335
		#define KEY_KP_EQUAL           336
		#define KEY_LEFT_SHIFT         340
		#define KEY_LEFT_CONTROL       341
		#define KEY_LEFT_ALT           342
		#define KEY_LEFT_SUPER         343
		#define KEY_RIGHT_SHIFT        344
		#define KEY_RIGHT_CONTROL      345
		#define KEY_RIGHT_ALT          346
		#define KEY_RIGHT_SUPER        347
		#define KEY_MENU               348
		#define KEY_LAST               KEY_MENU
	#endif

	#ifdef FR_LINUX
		#define KEY_RESERVED		0
		#define KEY_ESC			1
		#define KEY_1			2
		#define KEY_2			3
		#define KEY_3			4
		#define KEY_4			5
		#define KEY_5			6
		#define KEY_6			7
		#define KEY_7			8
		#define KEY_8			9
		#define KEY_9			10
		#define KEY_0			11
		#define KEY_MINUS		12
		#define KEY_EQUAL		13
		#define KEY_BACKSPACE		14
		#define KEY_TAB			15
		#define KEY_Q			16
		#define KEY_W			17
		#define KEY_E			18
		#define KEY_R			19
		#define KEY_T			20
		#define KEY_Y			21
		#define KEY_U			22
		#define KEY_I			23
		#define KEY_O			24
		#define KEY_P			25
		#define KEY_LEFTBRACE		26
		#define KEY_RIGHTBRACE		27
		#define KEY_ENTER		28
		#define KEY_LEFTCTRL		29
		#define KEY_A			30
		#define KEY_S			31
		#define KEY_D			32
		#define KEY_F			33
		#define KEY_G			34
		#define KEY_H			35
		#define KEY_J			36
		#define KEY_K			37
		#define KEY_L			38
		#define KEY_SEMICOLON		39
		#define KEY_APOSTROPHE		40
		#define KEY_GRAVE		41
		#define KEY_LEFTSHIFT		42
		#define KEY_BACKSLASH		43
		#define KEY_Z			44
		#define KEY_X			45
		#define KEY_C			46
		#define KEY_V			47
		#define KEY_B			48
		#define KEY_N			49
		#define KEY_M			50
		#define KEY_COMMA		51
		#define KEY_DOT			52
		#define KEY_SLASH		53
		#define KEY_RIGHTSHIFT		54
		#define KEY_KPASTERISK		55
		#define KEY_LEFTALT		56
		#define KEY_SPACE		57
		#define KEY_CAPSLOCK		58
		#define KEY_F1			59
		#define KEY_F2			60
		#define KEY_F3			61
		#define KEY_F4			62
		#define KEY_F5			63
		#define KEY_F6			64
		#define KEY_F7			65
		#define KEY_F8			66
		#define KEY_F9			67
		#define KEY_F10			68
		#define KEY_NUMLOCK		69
		#define KEY_SCROLLLOCK		70
		#define KEY_KP7			71
		#define KEY_KP8			72
		#define KEY_KP9			73
		#define KEY_KPMINUS		74
		#define KEY_KP4			75
		#define KEY_KP5			76
		#define KEY_KP6			77
		#define KEY_KPPLUS		78
		#define KEY_KP1			79
		#define KEY_KP2			80
		#define KEY_KP3			81
		#define KEY_KP0			82
		#define KEY_KPDOT		83

		#define KEY_ZENKAKUHANKAKU	85
		#define KEY_102ND		86
		#define KEY_F11			87
		#define KEY_F12			88
		#define KEY_RO			89
		#define KEY_KATAKANA		90
		#define KEY_HIRAGANA		91
		#define KEY_HENKAN		92
		#define KEY_KATAKANAHIRAGANA	93
		#define KEY_MUHENKAN		94
		#define KEY_KPJPCOMMA		95
		#define KEY_KPENTER		96
		#define KEY_RIGHTCTRL		97
		#define KEY_KPSLASH		98
		#define KEY_SYSRQ		99
		#define KEY_RIGHTALT		100
		#define KEY_LINEFEED		101
		#define KEY_HOME		102
		#define KEY_UP			103
		#define KEY_PAGEUP		104
		#define KEY_LEFT		105
		#define KEY_RIGHT		106
		#define KEY_END			107
		#define KEY_DOWN		108
		#define KEY_PAGEDOWN		109
		#define KEY_INSERT		110
		#define KEY_DELETE		111
		#define KEY_MACRO		112
		#define KEY_MUTE		113
		#define KEY_VOLUMEDOWN		114
		#define KEY_VOLUMEUP		115
		#define KEY_POWER		116	/* SC System Power Down */
		#define KEY_KPEQUAL		117
		#define KEY_KPPLUSMINUS		118
		#define KEY_PAUSE		119
		#define KEY_SCALE		120	/* AL Compiz Scale (Expose) */

	#endif
}